page cities with RTK
DachevM/project_gitflow pull request #4
Opened 2023-09-13 13:16 UTC by DachevM

2023-09-13 13:34 UTC, IgorKupaev requested changes

2023-09-13 13:34 UTC, IgorKupaev commented on package.json
> +    "axios": "^1.5.0",
чем обусловлено смена версии?

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Cities/CitiesItem.tsx
> +        {show && (
Передаешь туда show, делай проверку внутри
if (!show) return null;

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Cities/CitiesList.tsx
> +      ) : (
вынести в отдельный компонент и делать внутри проверку на isLoading

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Cities/CitiesList.tsx
> +          {cities.length > 0 ? (
тоже в отдельный компонент и проверку внутри делать

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Cities/CitiesList.tsx
> +            <p>Здесь пока нет городов</p>
Можно попробовать вынести этот параграф в отдельный компонент и принимать пропсом чего именно не хватает. Стилизовать его как нибудь и внедрить везде где "чего то не хватает"

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Orders/OrdersDescr.tsx
> +            <span>4 576 $</span>
Ценники фиксированные?

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Orders/OrdersDescr.tsx
> +            <span>4 576 $</span>
нужно что то придумать, может быть моки самому написать чтобы ценники не были захардкожены

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Orders/OrdersList.tsx
> +      {isLoading ? (
Вынести в отдельный компонент и сделать условие внутри

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/Pages/Orders/OrdersList.tsx
> +      {error && <h1>Ошибка 404</h1>}
Твой еррор тоже вынести в отдельный компонент, пропсами принимать error у внутри делать проверку
if (!error) return null
return ошибкак 404
и если нужно, принимать опциональный текст для него тоже пропсом.

Разработать этот компонент и внедрить во все приложение

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/UI/Loader/Loader.tsx
> +const Loader = () => {
Вот типо как у тебя лоадер вынесен, нужно вынести и еррор и Нет Данных

2023-09-13 13:34 UTC, IgorKupaev commented on src/Components/UI/PopUP/DeleteModal.tsx
> +  document.addEventListener("keydown", (e) => {
вынести в юзэффект и отписываться при анмаунте

2023-09-13 13:34 UTC, IgorKupaev commented on src/RTK/reducers/citiesReducer.ts
> +      state.error = "ошибка 404";
откуда ты знаешь что это 404*?

2023-09-13 13:34 UTC, IgorKupaev commented on src/RTK/reducers/orderReduce.ts
> +      state.error = "ошибка 404";
откуда 404?

2023-09-13 13:35 UTC, IgorKupaev commented
Если какие то комменты пересеклись с другими пр, то просто сделай в одной ветке, потом смерджишь

2023-09-14 09:31 UTC, DachevM commented on package.json
> +    "axios": "^1.5.0",
Ошибка вылезала, подумал, что из-за версии, но дело было в другом

2023-09-20 10:49 UTC, merged